# Generated by Django 5.1.1 on 2024-11-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_apiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
