# Generated by Django 4.2.11 on 2024-10-09 13:10

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationtype',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='country',
            name='state',
            field=models.ForeignKey(blank=True, default=base.models.State.active, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='state',
            field=models.ForeignKey(blank=True, default=base.models.State.active, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.ForeignKey(blank=True, default=base.models.State.active, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='state',
            field=models.ForeignKey(blank=True, default=base.models.State.active, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.state'),
        ),
    ]
