# Generated by Django 5.1.1 on 2024-10-04 09:00

import base.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_code', models.TextField(max_length=40, unique=True)),
                ('white_label', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('push_data_manually', models.BooleanField(default=False)),
                ('show_partial_report', models.BooleanField(default=False)),
                ('show_customer_phone_number', models.BooleanField(default=False)),
                ('show_customer_total', models.BooleanField(default=False)),
                ('show_customer_highest', models.BooleanField(default=False)),
                ('is_digital_advisor', models.BooleanField(default=False)),
                ('billing_plan', models.CharField(choices=[('Postpaid', 'Postpaid'), ('Prepaid', 'Prepaid')], default='Prepaid', max_length=8)),
                ('is_billable', models.BooleanField(default=True)),
                ('billable_effective', models.DateField(blank=True, null=True)),
                ('wallet_minimum_balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notification_email_on_wallet_balance', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount_charged_per_statement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('with_overdraft', models.BooleanField(default=False)),
                ('maximum_overdraft', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statement_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('statement_email_pass', models.CharField(blank=True, max_length=50, null=True)),
                ('query_no', models.IntegerField(default=1)),
                ('sync_db', models.BooleanField(default=False)),
                ('detailed_till_report', models.BooleanField(default=False)),
                ('api_feedback_enabled', models.BooleanField(default=False, help_text='Enable submission of results through webhook')),
                ('webhook_url', models.CharField(blank=True, max_length=200, null=True)),
                ('api_push_success_report', models.CharField(blank=True, choices=[('SCORES_ONLY', 'SCORES_ONLY'), ('FULL_JSON_SUMMARY', 'FULL_JSON_SUMMARY'), ('FILLING_PDF_REPORT', 'FILLING_PDF_REPORT')], default='FULL_JSON_SUMMARY', max_length=50, null=True)),
                ('webhook_auth_enabled', models.BooleanField(default=False, help_text='Authenticate on submission')),
                ('api_push_auth_method', models.CharField(blank=True, choices=[('BASIC_AUTH', 'BASIC_AUTH')], default='BASIC_AUTH', max_length=50, null=True)),
                ('api_basic_auth_username', models.CharField(blank=True, max_length=100, null=True)),
                ('api_basic_auth_password', models.CharField(blank=True, max_length=100, null=True)),
                ('special_callback_enabled', models.BooleanField(default=False, help_text='For special usecases')),
                ('special_callback_method', models.CharField(blank=True, max_length=100, null=True)),
                ('indebtedness_score', models.BooleanField(default=True)),
                ('impact_score', models.BooleanField(default=True)),
                ('activity_level_score', models.BooleanField(default=True)),
                ('income_score', models.BooleanField(default=True)),
                ('bs_income_score', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, default=base.models.Country.default_country, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.state')),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
    ]
